/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.distributedsystems.pw3;

import com.rabbitmq.client.BuiltinExchangeType;
import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;

public class ClientWriter {
    public static final String EXCHANGE_NAME= "writer";

    public static void main(String[] args) throws Exception {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost");

        try(Connection connection = factory.newConnection();
            Channel channel =connection.createChannel()){
            channel.exchangeDeclare(EXCHANGE_NAME, BuiltinExchangeType.FANOUT);
            String message = getMessage(args);
            channel.basicPublish(EXCHANGE_NAME, "", null, message.getBytes("UTF-8"));
        }
        catch (Exception e){
            System.err.println(e.getMessage());
        }
    }

    private static String getMessage(String[] args) throws Exception {
        if (args.length < 1) {
            throw new Exception("No message provided.");
        }

        return String.join(" ", args);
    }
}
