/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.rabbitmq:amqp-client:5.20.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.register<JavaExec>("send") {
    mainClass.set("edu.distributedsystems.pw1.Send")
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("receive") {
    mainClass.set("edu.distributedsystems.pw1.Receive")
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("emitLog") {
    mainClass.set("edu.distributedsystems.pw1.EmitLogDirect")
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("receiveLogs") {
    mainClass.set("edu.distributedsystems.pw1.ReceiveLogsDirect")
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
